AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for the AWS::S3Outposts::BucketPolicy resource type

Globals:
  Function:
    Timeout: 180  # docker start-up times can be long for SAM CLI
    MemorySize: 256

Resources:
  TypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: software.amazon.s3outposts.bucketpolicy.HandlerWrapper::handleRequest
      Runtime: java8
      CodeUri: ./target/aws-s3outposts-bucketpolicy-handler-1.0-SNAPSHOT.jar

  TestEntrypoint:
    Type: AWS::Serverless::Function
    Properties:
      Handler: software.amazon.s3outposts.bucketpolicy.HandlerWrapper::testEntrypoint
      Runtime: java8
      CodeUri: ./target/aws-s3outposts-bucketpolicy-handler-1.0-SNAPSHOT.jar
